name: cantos_esperanza_ruben_dario_libro_gratis
description: Libro Cantos de vida y esperanza de Rubén Darío gratuito.
version: 1.2.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_markdown: ^0.3.2
  share: ^0.6.3+5
  url_launcher: ^5.4.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/md/